In [1]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder , RobustScaler
from sklearn.metrics import mean_absolute_error , root_mean_squared_error , r2_score , mean_squared_error
from xgboost import XGBRegressor
import joblib

In [2]:
df = pd.read_csv("D:\Crop Prediction System\Model\Datasets\crop_production.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\premr\AppData\Local\Temp\ipykernel_16812\909646577.py:1: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_csv("D:\Crop Prediction System\Model\Datasets\crop_production.csv")

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [3]:
df.describe()

           Crop_Year          Area    Production
count  246091.000000  2.460910e+05  2.423610e+05
mean     2005.643018  1.200282e+04  5.825034e+05
std         4.952164  5.052340e+04  1.706581e+07
min      1997.000000  4.000000e-02  0.000000e+00
25%      2002.000000  8.000000e+01  8.800000e+01
50%      2006.000000  5.820000e+02  7.290000e+02
75%      2010.000000  4.392000e+03  7.023000e+03
max      2015.000000  8.580100e+06  1.250800e+09

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  str
 1   District_Name  246091 non-null  str
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  str
 4   Crop           246091 non-null  str
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.1 MB

In [5]:
df.isnull().sum()

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

In [6]:
df.isnull().mean()*100

State_Name       0.000000
District_Name    0.000000
Crop_Year        0.000000
Season           0.000000
Crop             0.000000
Area             0.000000
Production       1.515699
dtype: float64

In [7]:
df1=df[df["State_Name"] == "Madhya Pradesh"].reset_index(drop=True)

df1

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Madhya Pradesh,AGAR MALWA,2013,Kharif,Arhar/Tur,1834.0,739.0
1,Madhya Pradesh,AGAR MALWA,2013,Kharif,Bajra,5.0,4.0
2,Madhya Pradesh,AGAR MALWA,2013,Kharif,Barley,286.0,466.0
3,Madhya Pradesh,AGAR MALWA,2013,Kharif,Groundnut,1077.0,1138.0
4,Madhya Pradesh,AGAR MALWA,2013,Kharif,Jowar,2750.0,3347.0
...,...,...,...,...,...,...,...
22938,Madhya Pradesh,VIDISHA,2013,Whole Year,Onion,176.0,1562.0
22939,Madhya Pradesh,VIDISHA,2013,Whole Year,Potato,243.0,2561.0
22940,Madhya Pradesh,VIDISHA,2013,Whole Year,Sesamum,279.0,124.0
22941,Madhya Pradesh,VIDISHA,2013,Whole Year,Sugarcane,47.0,950.0
22942,Madhya Pradesh,VIDISHA,2013,Whole Year,Sweet potato,40.0,317.0

In [8]:
df1.drop(columns=["State_Name"], inplace=True)
df1

      District_Name  Crop_Year       Season          Crop    Area  Production
0        AGAR MALWA       2013  Kharif          Arhar/Tur  1834.0       739.0
1        AGAR MALWA       2013  Kharif              Bajra     5.0         4.0
2        AGAR MALWA       2013  Kharif             Barley   286.0       466.0
3        AGAR MALWA       2013  Kharif          Groundnut  1077.0      1138.0
4        AGAR MALWA       2013  Kharif              Jowar  2750.0      3347.0
...             ...        ...          ...           ...     ...         ...
22938       VIDISHA       2013  Whole Year          Onion   176.0      1562.0
22939       VIDISHA       2013  Whole Year         Potato   243.0      2561.0
22940       VIDISHA       2013  Whole Year        Sesamum   279.0       124.0
22941       VIDISHA       2013  Whole Year      Sugarcane    47.0       950.0
22942       VIDISHA       2013  Whole Year   Sweet potato    40.0       317.0

[22943 rows x 6 columns]

In [9]:
df1.isnull().sum()

District_Name      0
Crop_Year          0
Season             0
Crop               0
Area               0
Production       339
dtype: int64

In [10]:
df1.isnull().mean()*100

District_Name    0.000000
Crop_Year        0.000000
Season           0.000000
Crop             0.000000
Area             0.000000
Production       1.477575
dtype: float64

In [11]:
df1.dropna(subset=["Production"],inplace=True)

In [12]:
df1.isnull().mean()*100

District_Name    0.0
Crop_Year        0.0
Season           0.0
Crop             0.0
Area             0.0
Production       0.0
dtype: float64

In [13]:
df1.count()

District_Name    22604
Crop_Year        22604
Season           22604
Crop             22604
Area             22604
Production       22604
dtype: int64

In [14]:
df1["District_Name"]=df1["District_Name"].str.title()
df1

      District_Name  Crop_Year       Season          Crop    Area  Production
0        Agar Malwa       2013  Kharif          Arhar/Tur  1834.0       739.0
1        Agar Malwa       2013  Kharif              Bajra     5.0         4.0
2        Agar Malwa       2013  Kharif             Barley   286.0       466.0
3        Agar Malwa       2013  Kharif          Groundnut  1077.0      1138.0
4        Agar Malwa       2013  Kharif              Jowar  2750.0      3347.0
...             ...        ...          ...           ...     ...         ...
22938       Vidisha       2013  Whole Year          Onion   176.0      1562.0
22939       Vidisha       2013  Whole Year         Potato   243.0      2561.0
22940       Vidisha       2013  Whole Year        Sesamum   279.0       124.0
22941       Vidisha       2013  Whole Year      Sugarcane    47.0       950.0
22942       Vidisha       2013  Whole Year   Sweet potato    40.0       317.0

[22604 rows x 6 columns]

In [15]:
df1["Yield"] = round(df1["Production"]/df1["Area"],2)
df1

,District_Name,Crop_Year,Season,Crop,Area,Production,Yield
0,Agar Malwa,2013,Kharif,Arhar/Tur,1834.0,739.0,0.40
1,Agar Malwa,2013,Kharif,Bajra,5.0,4.0,0.80
2,Agar Malwa,2013,Kharif,Barley,286.0,466.0,1.63
3,Agar Malwa,2013,Kharif,Groundnut,1077.0,1138.0,1.06
4,Agar Malwa,2013,Kharif,Jowar,2750.0,3347.0,1.22
...,...,...,...,...,...,...,...
22938,Vidisha,2013,Whole Year,Onion,176.0,1562.0,8.88
22939,Vidisha,2013,Whole Year,Potato,243.0,2561.0,10.54
22940,Vidisha,2013,Whole Year,Sesamum,279.0,124.0,0.44
22941,Vidisha,2013,Whole Year,Sugarcane,47.0,950.0,20.21
22942,Vidisha,2013,Whole Year,Sweet potato,40.0,317.0,7.92

In [16]:
df2=df1.drop(columns=["Production", "Area"])
df2

      District_Name  Crop_Year       Season          Crop  Yield
0        Agar Malwa       2013  Kharif          Arhar/Tur   0.40
1        Agar Malwa       2013  Kharif              Bajra   0.80
2        Agar Malwa       2013  Kharif             Barley   1.63
3        Agar Malwa       2013  Kharif          Groundnut   1.06
4        Agar Malwa       2013  Kharif              Jowar   1.22
...             ...        ...          ...           ...    ...
22938       Vidisha       2013  Whole Year          Onion   8.88
22939       Vidisha       2013  Whole Year         Potato  10.54
22940       Vidisha       2013  Whole Year        Sesamum   0.44
22941       Vidisha       2013  Whole Year      Sugarcane  20.21
22942       Vidisha       2013  Whole Year   Sweet potato   7.92

[22604 rows x 5 columns]

In [17]:
df2.columns

Index(['District_Name', 'Crop_Year', 'Season', 'Crop', 'Yield'], dtype='str')

In [18]:
categorical_col = ['District_Name', 'Season', 'Crop']

In [19]:
preprocessor = ColumnTransformer(
    transformers=[
        ("encoding", OneHotEncoder(sparse_output=False, handle_unknown='ignore'), categorical_col),
        ("scailing", RobustScaler(), ['Crop_Year'])
    ],
    remainder='passthrough'
)

In [20]:
pipeline = Pipeline(
    steps=[
        ("preproccessor",preprocessor),
        ("xgb", XGBRegressor(

            n_estimators=300,
            max_depth = 3,
            learning_rate=0.03,
            reg_alpha = 0.1,
            reg_lambda=1.5,
            subsample=0.7,
            colsample_bytree=0.7,
            n_jobs=-1,
            random_state = 42,
            min_child_weight=2,

        ))
    ]
)

In [21]:
X=df2.drop(columns=["Yield"])
X

      District_Name  Crop_Year       Season          Crop
0        Agar Malwa       2013  Kharif          Arhar/Tur
1        Agar Malwa       2013  Kharif              Bajra
2        Agar Malwa       2013  Kharif             Barley
3        Agar Malwa       2013  Kharif          Groundnut
4        Agar Malwa       2013  Kharif              Jowar
...             ...        ...          ...           ...
22938       Vidisha       2013  Whole Year          Onion
22939       Vidisha       2013  Whole Year         Potato
22940       Vidisha       2013  Whole Year        Sesamum
22941       Vidisha       2013  Whole Year      Sugarcane
22942       Vidisha       2013  Whole Year   Sweet potato

[22604 rows x 4 columns]

In [22]:
y = df2["Yield"]
y

0         0.40
1         0.80
2         1.63
3         1.06
4         1.22
         ...
22938     8.88
22939    10.54
22940     0.44
22941    20.21
22942     7.92
Name: Yield, Length: 22604, dtype: float64

In [23]:
X_train , X_test , y_train , y_test = train_test_split(X , y ,test_size=0.3 ,random_state=42)

In [24]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preproccessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoding',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['District_Name', 'Season',
                                                   'Crop']),
                                                 ('scailing', RobustScaler(),
                                                  ['Crop_Year'])])),
                ('xgb',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              c...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.03,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=3, max_leaves=None, min_child_weight=2,
                              missing=nan, monotone_constraints=None,
                              multi_strategy=None, n_estimators=300, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [25]:
y_pred = pipeline.predict(X_test)

In [26]:

print(f"- Mean Absolute Error (MAE): {mean_absolute_error(y_test, y_pred):.3f}")
print(f"- Root Mean Squared Error (RMSE): {root_mean_squared_error(y_test, y_pred):.3f}")
print(f"- R2 Score: {r2_score(y_test, y_pred)*100:.3f}%")

- Mean Absolute Error (MAE): 1.144
- Root Mean Squared Error (RMSE): 3.203
- R2 Score: 81.158%

In [27]:
param_grid = {
    'xgb__n_estimators': [100, 200, 300 ],
    'xgb__max_depth': [3,2],
    'xgb__learning_rate': [0.01, 0.03,],
    'xgb__subsample': [0.7, 0.75, 0.6,0.8]
}

from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring='r2',
    cv=3,
    n_jobs=-1,
    verbose=2
)

print("Starting GridSearchCV...")
grid_search.fit(X_train, y_train)
print("GridSearchCV completed.")

Starting GridSearchCV...
Fitting 3 folds for each of 48 candidates, totalling 144 fits
GridSearchCV completed.

In [28]:
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best R2 score from cross-validation: {grid_search.best_score_:.3f}")


best_model = grid_search.best_estimator_

Best parameters found: {'xgb__learning_rate': 0.03, 'xgb__max_depth': 3, 'xgb__n_estimators': 300, 'xgb__subsample': 0.8}
Best R2 score from cross-validation: 0.801

In [29]:
y_pred_tuned = best_model.predict(X_test)
y_pred_train = best_model.predict(X_train)

print(f"\nPerformance of the Tuned Model on the Train Set:")
print(mean_absolute_error(y_train, y_pred_train))
print(root_mean_squared_error(y_train, y_pred_train))
print(r2_score(y_train, y_pred_train) * 100,"\n")

mae_tuned = mean_absolute_error(y_test, y_pred_tuned)
rmse_tuned = root_mean_squared_error(y_test, y_pred_tuned)
r2_tuned = r2_score(y_test, y_pred_tuned) * 100

print(f"\nPerformance of the Tuned Model on the Test Set:")
print(f"- Mean Absolute Error (MAE): {mae_tuned:.3f}")
print(f"- Root Mean Squared Error (RMSE): {rmse_tuned:.3f}")
print(f"- R2 Score: {r2_tuned:.3f}%")

print("\nOriginal Model Performance ")
print(f"- Mean Absolute Error (MAE): {mean_absolute_error(y_test, y_pred):.3f}")
print(f"- Root Mean Squared Error (RMSE): {root_mean_squared_error(y_test, y_pred):.3f}")
print(f"- R2 Score: {r2_score(y_test, y_pred)*100:.3f}%")

Performance of the Tuned Model on the Train Set:
1.1576084494900045
3.1377957473367686
83.4151897524954


Performance of the Tuned Model on the Test Set:
- Mean Absolute Error (MAE): 1.141
- Root Mean Squared Error (RMSE): 3.203
- R2 Score: 81.166%

Original Model Performance
- Mean Absolute Error (MAE): 1.144
- Root Mean Squared Error (RMSE): 3.203
- R2 Score: 81.158%

In [30]:
joblib.dump(pipeline, "Crop_production.pkl")

['Crop_production.pkl']